# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  
    desc "Sync certificates"
 lane :sync_certificates do
   #read-only disables match from overriding the existing certificates.
   match({readonly: true, type: "appstore"})
 end
 
 desc "Create ipa"
 lane :build do
   #update profiles
   sync_certificates
   # Increases the build number by 1
   increment_build_number
   # Creates a signed file
   gym
 end
 
 desc "Manual Release to TestFlight"
 lane :beta do
   build
   pilot
 end
 
 desc "Automated Release to TestFlight"
 lane :ghbeta do
    setup_ci if ENV['CI']
    match(type: 'development')
    increment_build_number
    build_app
    upload_to_testflight(skip_waiting_for_build_processing: true)
 end
end

