name: Release on TestFlight
on:
  workflowworkflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: fastlane ghbeta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
